## Descriptions:
Process 2 variables from demograhics table, using cohort2
- Process language --> English: yes/no
- Process insurance (medicare/caid/cal/mcal/mcare/na) --> yes/no

**Changes:**
- Use shc_core_2021
- Remove any `recent_date` related contents

**Inputs**: 
- `6_2_cohort2`: updated `6_1_cohort1` with inc/exc criteria, which also has demographics information

**Outputs**: 
- `3_coh2_demo`

### Importing R libraries

In [1]:
library(bigrquery)  # to query STARR-OMOP (stored in BigQuery) using SQL
library(tidyverse)
library(lubridate)
# library(mice)
# library(VIM) # for missing data plot

# library(data.table)
# library(Matrix)
# library(caret) # import this before glmnet to avoid rlang version problem
# library(glmnet)
# library(bit64)

# library(slam)
# library(mtools) for one hot coder, not available on Nero or use caret or tidyr
options(repr.matrix.max.rows=250, repr.matrix.max.cols=30)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.3     ✔ purrr   0.3.4
✔ tibble  3.1.2     ✔ dplyr   1.0.6
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()


Attaching package: ‘lubridate’


The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union

### Demographic variables
- Age (only >=18): done in in/ex criteria
- insurance = Medical/care/caid and n/a insurance --> medis =1 otherwise 0
- language --> Engl = 1 for English, otherwise 0
- leave height and weight to be processed with flowsheet age (>=18 only)

In [3]:
# datadir = "../../DataTD"
datadir = "../../DataTD/shc2021"
outdir = "../../OutputTD/shc2021"

cohort <- read.csv(file.path(outdir, "2_cohort2.csv"))
nrow(cohort) # 17128
summary(cohort)

[1] 63050

   anon_id          pat_enc_csn_id_coded admit_time_jittered     label
 Length:63050       Min.   :1.311e+11    Length:63050        Min.   :0.000
 Class :character   1st Qu.:1.312e+11    Class :character    1st Qu.:0.000
 Mode  :character   Median :1.313e+11    Mode  :character    Median :0.000
                    Mean   :1.312e+11                        Mean   :0.139
                    3rd Qu.:1.313e+11                        3rd Qu.:0.000
                    Max.   :1.313e+11                        Max.   :1.000

  admit_time           adm_year      adm_month      inpatient_data_id_coded
 Length:63050       Min.   :2015   Min.   : 1.000   Min.   :18839023
 Class :character   1st Qu.:2016   1st Qu.: 3.000   1st Qu.:27991297
 Mode  :character   Median :2018   Median : 6.000   Median :38223187
                    Mean   :2018   Mean   : 6.347   Mean   :41283830
                    3rd Qu.:2020   3rd Qu.: 9.000   3rd Qu.:54060667
                    Max.   :2021   Max.   :12.000   Max.   :73231043

      ESI        hosp_admsn_time      ed_time_hr         gender
 Min.   :1.000   Length:63050       Min.   :  0.000   Length:63050
 1st Qu.:2.000   Class :character   1st Qu.:  2.233   Class :character
 Median :3.000   Mode  :character   Median :  3.450   Mode  :character
 Mean   :2.625                      Mean   :  4.637
 3rd Qu.:3.000                      3rd Qu.:  5.200
 Max.   :5.000                      Max.   :190.433
 NA's   :1967
     race             language         recent_height_cm recent_weight_kg
 Length:63050       Length:63050       Min.   : 12.95   Min.   :  0.10
 Class :character   Class :character   1st Qu.:160.02   1st Qu.: 60.90
 Mode  :character   Mode  :character   Median :167.64   Median : 73.30
                                       Mean   :168.01   Mean   : 76.73
                                       3rd Qu.:175.30   3rd Qu.: 88.30
                                       Max.   :213.36   Max.   :504.85
                                       NA's   :1658     NA's   :284
  insurance              age
 Length:63050       Min.   : 18.00
 Class :character   1st Qu.: 45.00
 Mode  :character   Median : 61.00
                    Mean   : 58.82
                    3rd Qu.: 73.00
                    Max.   :118.00

In [4]:
head(cohort, n=1)

  anon_id   pat_enc_csn_id_coded admit_time_jittered       label
1 JC1000116 131066472308         2015-01-28 00:46:00+00:00 0
  admit_time          adm_year adm_month inpatient_data_id_coded ESI
1 2015-01-28 00:46:00 2015     1         19328596                3
  hosp_admsn_time     ed_time_hr gender race  language recent_height_cm
1 2015-01-27 04:24:00 20.36667   Female Other Spanish  154
  recent_weight_kg insurance age
1 73.05            HPSM      38

In [5]:
cohort <- cohort %>% select(-hosp_admsn_time, -ed_time_hr) %>% # hosp_admsn_time = ymd_hms(hosp_admsn_time)
                mutate(admit_time = ymd_hms(admit_time), # recent_date = ymd(recent_date), 
                       gender = factor(gender), race = factor(race), language = factor(language), insurance = factor(insurance)) 
                
nrow(cohort)
summary(cohort)

[1] 63050

   anon_id          pat_enc_csn_id_coded admit_time_jittered     label
 Length:63050       Min.   :1.311e+11    Length:63050        Min.   :0.000
 Class :character   1st Qu.:1.312e+11    Class :character    1st Qu.:0.000
 Mode  :character   Median :1.313e+11    Mode  :character    Median :0.000
                    Mean   :1.312e+11                        Mean   :0.139
                    3rd Qu.:1.313e+11                        3rd Qu.:0.000
                    Max.   :1.313e+11                        Max.   :1.000

   admit_time                     adm_year      adm_month
 Min.   :2015-01-01 04:52:00   Min.   :2015   Min.   : 1.000
 1st Qu.:2016-12-27 04:51:15   1st Qu.:2016   1st Qu.: 3.000
 Median :2018-11-15 00:08:30   Median :2018   Median : 6.000
 Mean   :2018-09-02 16:29:46   Mean   :2018   Mean   : 6.347
 3rd Qu.:2020-05-27 07:31:15   3rd Qu.:2020   3rd Qu.: 9.000
 Max.   :2021-09-30 07:00:00   Max.   :2021   Max.   :12.000

 inpatient_data_id_coded      ESI            gender
 Min.   :18839023        Min.   :1.000   Female :29971
 1st Qu.:27991297        1st Qu.:2.000   Male   :33072
 Median :38223187        Median :3.000   Unknown:    7
 Mean   :41283830        Mean   :2.625
 3rd Qu.:54060667        3rd Qu.:3.000
 Max.   :73231043        Max.   :5.000
                         NA's   :1967
               race             language     recent_height_cm recent_weight_kg
 Asian           : 9713   English   :52631   Min.   : 12.95   Min.   :  0.10
 Black           : 4409   Spanish   : 5412   1st Qu.:160.02   1st Qu.: 60.90
 Native American :  262   Mandarin  :  990   Median :167.64   Median : 73.30
 Other           :15029   Vietnamese:  766   Mean   :168.01   Mean   : 76.73
 Pacific Islander: 1301   Cantonese :  393   3rd Qu.:175.30   3rd Qu.: 88.30
 Unknown         :  440   Russian   :  363   Max.   :213.36   Max.   :504.85
 White           :31896   (Other)   : 2495   NA's   :1658     NA's   :284
       insurance          age
 MEDICARE   :23706   Min.   : 18.00
 BLUE CROSS : 4463   1st Qu.: 45.00
 HPSM       : 4243   Median : 61.00
            : 3672   Mean   : 58.82
 MEDI-CAL   : 2581   3rd Qu.: 73.00
 BLUE SHIELD: 2578   Max.   :118.00
 (Other)    :21807

In [6]:
# checking duplicates
nrow(cohort %>% select(anon_id) %>% distinct()) # 31511
nrow(cohort %>% select(anon_id, pat_enc_csn_id_coded) %>% distinct()) # 45794
cohort[duplicated(cohort[, c('anon_id','pat_enc_csn_id_coded')]),]

# cohort %>% filter(anon_id == "JCd49287") # pat_enc_csn_id_coded = 131195706986, 
# cohort <- cohort %>% filter (!(anon_id == "JCd49287" & race == "Unknown"))

[1] 42037

[1] 63050

     anon_id pat_enc_csn_id_coded admit_time_jittered label admit_time adm_year
     adm_month inpatient_data_id_coded ESI gender race language
     recent_height_cm recent_weight_kg insurance age

In [7]:
summary(cohort %>% select(ESI, gender, race, recent_height_cm, recent_weight_kg, age))
cohort %>% gather(var, value) %>% distinct() %>% count(var) %>% arrange(n)
cohort %>% summarise_each(funs(n_distinct))

      ESI            gender                    race       recent_height_cm
 Min.   :1.000   Female :29971   Asian           : 9713   Min.   : 12.95
 1st Qu.:2.000   Male   :33072   Black           : 4409   1st Qu.:160.02
 Median :3.000   Unknown:    7   Native American :  262   Median :167.64
 Mean   :2.625                   Other           :15029   Mean   :168.01
 3rd Qu.:3.000                   Pacific Islander: 1301   3rd Qu.:175.30
 Max.   :5.000                   Unknown         :  440   Max.   :213.36
 NA's   :1967                    White           :31896   NA's   :1658
 recent_weight_kg      age
 Min.   :  0.10   Min.   : 18.00
 1st Qu.: 60.90   1st Qu.: 45.00
 Median : 73.30   Median : 61.00
 Mean   : 76.73   Mean   : 58.82
 3rd Qu.: 88.30   3rd Qu.: 73.00
 Max.   :504.85   Max.   :118.00
 NA's   :284

Warning message:
“attributes are not identical across measure variables;
they will be dropped”

   var                     n
1  label                       2
2  gender                      3
3  ESI                         6
4  adm_year                    7
5  race                        7
6  adm_month                  12
7  language                   56
8  age                        93
9  insurance                 117
10 recent_height_cm          876
11 recent_weight_kg         3721
12 anon_id                 42037
13 admit_time              62315
14 admit_time_jittered     62315
15 inpatient_data_id_coded 63050
16 pat_enc_csn_id_coded    63050

Warning message:
“`summarise_each_()` was deprecated in dplyr 0.7.0.
Please use `across()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.”
Warning message:
“`funs()` was deprecated in dplyr 0.8.0.
Please use a list of either functions or lambdas:

  # Simple named list:
  list(mean = mean, median = median)

  # Auto named with `tibble::lst()`:
  tibble::lst(mean, median)

  # Using lambdas
  list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.”

  anon_id pat_enc_csn_id_coded admit_time_jittered label admit_time adm_year
1 42037   63050                62315               2     62315      7
  adm_month inpatient_data_id_coded ESI gender race language recent_height_cm
1 12        63050                   6   3      7    56       876
  recent_weight_kg insurance age
1 3721             117       93

### Insurance:

In [8]:
options(repr.matrix.max.rows=135, repr.matrix.max.cols=20)
cohort %>%                 # filter(!is.na(col)) %>% filter out all rows with NAs in col 
                group_by(insurance) %>% count() %>% arrange(desc(n))

    insurance                                         n
1   MEDICARE                                          23706
2   BLUE CROSS                                         4463
3   HPSM                                               4243
4                                                      3672
5   MEDI-CAL                                           2581
6   BLUE SHIELD                                        2578
7   SANTA CLARA FAMILY HP                              2443
8   UNITED HEALTHCARE                                  2119
9   AETNA                                              1667
10  HPSM - MCARE ADV                                   1465
11  CIGNA                                              1311
12  BLUE CARD (OUT OF STATE)                           1219
13  MCAL HMO - CENTRAL CALIFORNIA ALLIANCE FOR HEALTH  1022
14  ALAMEDA ALLIANCE MCAL MGD CARE                     1011
15  HEALTHNET                                           814
16  UHC MEDICARE AARP COMPLETE                          664
17  BLUE CROSS MEDI-CAL                                 634
18  UNITED HEALTHCARE SR ADV                            616
19  SCFHP - MCARE ADV                                   553
20  BLUE CARD (OUT OF STATE) - BS                       451
21  SNF HOSPICE MEDICARE (HOSP ONLY)                    383
22  HEALTHNET SENIOR ADVANTAGE                          365
23  AETNA CHOICE POS II SHC                             359
24  MEDICARE SENIOR ADVANTAGE - OTHER                   300
25  UMR                                                 297
26  MEDI-CAL MANAGED CARE                               249
27  COMMERCIAL OTHER                                    241
28  VETERANS ADMINISTRATION                             239
29  MCAL HP OF SAN JOAQUIN                              233
30  PHP OF CA                                           210
31  BLUE CROSS SENIOR                                   206
32  AETNA SENIOR                                        179
33  TRICARE HEALTH NET                                  162
34  KAISER NORTHERN CA                                  154
35  TRIWEST                                             146
36  AARP                                                139
37  MCAL HMO-HEALTHNET                                  134
38  VALLEY HEALTH PLAN                                  134
39  ALIGNMENT HEALTH PLAN                               126
40  MANAGED CARE OTHER                                  120
41  HUMANA GOLD CHOICE                                  110
42  MCAL CONTRA COSTA HEALTH PLAN                       106
43  MEDICAID                                            102
44  MCAL HMO-SAN FRANCISCO HEALTH PLN                    93
45  UNITEDHEALTHCARE WEST                                90
46  MCAL CENCAL                                          71
47  SHC ADVANTAGE SUTTER                                 67
48  CAREMORE ANTHEM SR ADV                               65
49  KAISER SENIOR                                        63
50  SUTTER HEALTH PLUS                                   52
51  VISION SERVICES PLAN                                 47
52  FIRST HEALTH                                         45
53  HUMANA CHOICE CARE                                   40
54  MEDI-CAL CCS                                         33
55  PRIVATE HEALTHCARE SYS (PHCS)                        28
56  MULTIPLAN                                            27
57  ZZZTRICARE UHC M AND V                               27
58  BRAND NEW DAY SR ADV                                 24
59  PATHWAYS (HOSPITAL ONLY)                             22
60  TRICARE FOR LIFE                                     20
61  COVID19 HRSA UNINSURED FUND                          19
62  SUTTER HEALTH SYSTEM                                 19
63  BSCA PROMISE HEALTH SR ADV                           17
64  BLUE CARD SR ADV (OUT OF STATE) - BX                 15
65  INTERNATIONAL                                        14
66  MEDI-CAL MGD CARE COUNTY                             14
67  COM-OTHER                                            13
68  GOV-OTHER                                            13
69  ASPIRE HEALTH PLAN SR ADV                            12
70  HOMETOWN HEALTH PLAN                                 12
71  MCAL KAISER                                          12
72  MUTUAL OF OMAHA                                      11
73  BLUE SHIELD SENIOR                                   10
74  MCAL HMO-MOLINA                                       9
75  BLUE CARD SR ADV (OUT OF STATE) - BS                  8
76  CHAMPVA                                               7
77  GOLDEN STATE MHP                                      7
78  ARRILLAGA STUDENT ATHLETE                             6
79  INTERPLAN                                             6
80  VITALITY HEALTH PLAN SR ADV                           6
81  BENEFIT RISK MGMT                                     5
82  MEDICAID HMO                                          5
83  OPTUM HEALTH/URN                                      5
84  UNITED HEALTH CARE                                    5
85  BLUE CARD-BX/BS OUT-OF-STATE                          4
86  HEALTH NET                                            4
87  HOMETOWN HP SENIOR                                    4
88  NETWORKS BY DESIGN                                    4
89  SCAN HEALTH PLAN                                      4
90  COVENTRY HEALTH CARE                                  3
91  MCAL CALOPTIMA                                        3
92  MCAL KAISER SANTA CLARA                               3
93  AETNA SUTTER HEALTH                                   2
94  ALAMEDA ALLIANCE GROUP CARE                           2
95  GEHA                                                  2
96  HPSM - CCS                                            2
97  PHYSICIANS FOUNDATION                                 2
98  SHCA COMM AETNA                                       2
99  CCS HEALTH PLAN SAN MATEO                             1
100 CCS MEDI-CAL                                          1
101 DONOR NETWORK WEST                                    1
102 JOHN MUIR                                             1
103 MEDI-CAL MGD CARE NON-COUNTY                          1
104 NORTHERN NEVADA TRUST FUND                            1
105 OPTUM                                                 1
106 OPTUM HEALTH MEDICARE MANAGED CARE TRANSPLANT         1
107 PARTNERSHIP HEALTH CCS                                1
108 SAMARITAN CHOICE PLAN                                 1
109 SUTTER HEALTH                                         1
110 THE SEQUOIAS                                          1
111 UHC DUAL COMPLETE                                     1
112 UHC MEDICARE AARP COMPLETE PPO                        1
113 UHC WEST                                              1
114 USA MANAGED CARE SENIOR                               1
115 VICTIM VIOLENT CRIME                                  1
116 WELLCARE SENIOR                                       1
117 ZZZALAMEDA ALLIANCE MEDICARE ADV-                     1

In [9]:
# check for medicare/ medical/ no insurance
# cohort %>% filter(str_detect(insurance, "MEDI") | insurance == "") %>% 
#                 group_by(insurance) %>% count() %>% arrange(-n)

# mcal = medical, mcare = medicare
medis <- c("MEDI", "MCAL", "MCARE")
cohort %>% filter(str_detect(insurance, paste(medis, collapse = "|")) | insurance == "") %>% 
                group_by(insurance) %>% count() %>% arrange(-n)

   insurance                                         n
1  MEDICARE                                          23706
2                                                     3672
3  MEDI-CAL                                           2581
4  HPSM - MCARE ADV                                   1465
5  MCAL HMO - CENTRAL CALIFORNIA ALLIANCE FOR HEALTH  1022
6  ALAMEDA ALLIANCE MCAL MGD CARE                     1011
7  UHC MEDICARE AARP COMPLETE                          664
8  BLUE CROSS MEDI-CAL                                 634
9  SCFHP - MCARE ADV                                   553
10 SNF HOSPICE MEDICARE (HOSP ONLY)                    383
11 MEDICARE SENIOR ADVANTAGE - OTHER                   300
12 MEDI-CAL MANAGED CARE                               249
13 MCAL HP OF SAN JOAQUIN                              233
14 MCAL HMO-HEALTHNET                                  134
15 MCAL CONTRA COSTA HEALTH PLAN                       106
16 MEDICAID                                            102
17 MCAL HMO-SAN FRANCISCO HEALTH PLN                    93
18 MCAL CENCAL                                          71
19 MEDI-CAL CCS                                         33
20 MEDI-CAL MGD CARE COUNTY                             14
21 MCAL KAISER                                          12
22 MCAL HMO-MOLINA                                       9
23 MEDICAID HMO                                          5
24 MCAL CALOPTIMA                                        3
25 MCAL KAISER SANTA CLARA                               3
26 CCS MEDI-CAL                                          1
27 MEDI-CAL MGD CARE NON-COUNTY                          1
28 OPTUM HEALTH MEDICARE MANAGED CARE TRANSPLANT         1
29 UHC MEDICARE AARP COMPLETE PPO                        1
30 ZZZALAMEDA ALLIANCE MEDICARE ADV-                     1

In [10]:
# turn insurance into medis which has "MEDI" under insurance
# insurance = 0 if patient has medis or no insurance, 1 for other insurance
medis <- c("MEDI", "MCAL", "MCARE")

nrow(cohort %>% filter(insurance == "")) # 2737
nrow(cohort %>% filter(str_detect(insurance, "MEDI"))) # 20766
nrow(cohort %>% filter(str_detect(insurance, paste(medis, collapse = "|")))) # 23987

cohort_demo <- cohort %>%
                    mutate(insurance = ifelse(str_detect(insurance, paste(medis, collapse = "|")) | insurance == "", 0, 1)) %>%
                    group_by(anon_id, pat_enc_csn_id_coded) %>%
                    mutate(insurance = sum(insurance)) %>% ungroup() %>% # just to make sure if anyone else has more than 1
                    mutate(insurance = ifelse(insurance>0, 1, insurance)) 

cohort_demo %>% count(insurance)

[1] 3672

[1] 28676

[1] 33391

  insurance n
1 0         37063
2 1         25987

### Language:

In [11]:
cohort_demo %>% group_by(language) %>% count() %>% arrange(desc(n))

   language               n
1  English                52631
2  Spanish                 5412
3  Mandarin                 990
4  Vietnamese               766
5  Cantonese                393
6  Russian                  363
7  Farsi                    339
8  Tongan                   323
9  Tagalog                  256
10 Korean                   203
11 Hindi                    182
12 Other                    168
13 Dari                     157
14 Punjabi (Panjabi)        155
15 Arabic                   103
16 Japanese                  61
17 Portuguese                52
18 Unknown                   41
19 Deaf/Non-Sign Language    40
20 Burmese                   38
21 Urdu                      36
22 Samoan                    33
23 French                    27
24 Gujarati                  26
25 American Sign Language    24
26                           21
27 Italian                   21
28 Cambodian, Mon-Khmer      20
29 Greek                     16
30 Telugu                    16
31 Polish                    15
32 Persian                   14
33 Albanian                  11
34 Hmong                     11
35 Romanian                  10
36 Indonesian                 9
37 Laotian                    9
38 Hebrew                     8
39 Amharic                    7
40 Armenian                   7
41 Ilocano                    5
42 Taiwanese                  4
43 Hungarian                  3
44 Serbian                    3
45 Thai                       3
46 Traditional Chinese        3
47 Croatian                   2
48 Fijian                     2
49 German                     2
50 Mien (lu Mien)             2
51 Nepali                     2
52 Bosnian                    1
53 Canadian French            1
54 Creole, French             1
55 Haitian Creole             1
56 Yoruba                     1

In [12]:
cohort_demo <- cohort_demo %>%
                    mutate(English = ifelse(language == "English", 1, 0)) %>% 
                    select(-c(language))

cohort_demo %>% count(English)
nrow(cohort_demo)
length(unique(cohort_demo$anon_id))
summary(cohort_demo %>% select(ESI, gender, race, recent_height_cm, recent_weight_kg, age, insurance, English))

  English n
1 0       10419
2 1       52631

[1] 63050

[1] 42037

      ESI            gender                    race       recent_height_cm
 Min.   :1.000   Female :29971   Asian           : 9713   Min.   : 12.95
 1st Qu.:2.000   Male   :33072   Black           : 4409   1st Qu.:160.02
 Median :3.000   Unknown:    7   Native American :  262   Median :167.64
 Mean   :2.625                   Other           :15029   Mean   :168.01
 3rd Qu.:3.000                   Pacific Islander: 1301   3rd Qu.:175.30
 Max.   :5.000                   Unknown         :  440   Max.   :213.36
 NA's   :1967                    White           :31896   NA's   :1658
 recent_weight_kg      age           insurance         English
 Min.   :  0.10   Min.   : 18.00   Min.   :0.0000   Min.   :0.0000
 1st Qu.: 60.90   1st Qu.: 45.00   1st Qu.:0.0000   1st Qu.:1.0000
 Median : 73.30   Median : 61.00   Median :0.0000   Median :1.0000
 Mean   : 76.73   Mean   : 58.82   Mean   :0.4122   Mean   :0.8348
 3rd Qu.: 88.30   3rd Qu.: 73.00   3rd Qu.:1.0000   3rd Qu.:1.0000
 Max.   :504.85   Max.   :118.00   Max.   :1.0000   Max.   :1.0000
 NA's   :284

In [13]:
head(cohort_demo, n=1)
colnames(cohort_demo)

  anon_id   pat_enc_csn_id_coded admit_time_jittered       label
1 JC1000116 131066472308         2015-01-28 00:46:00+00:00 0
  admit_time          adm_year adm_month inpatient_data_id_coded ESI gender
1 2015-01-28 00:46:00 2015     1         19328596                3   Female
  race  recent_height_cm recent_weight_kg insurance age English
1 Other 154              73.05            1         38  0

 [1] "anon_id"                 "pat_enc_csn_id_coded"
 [3] "admit_time_jittered"     "label"
 [5] "admit_time"              "adm_year"
 [7] "adm_month"               "inpatient_data_id_coded"
 [9] "ESI"                     "gender"
[11] "race"                    "recent_height_cm"
[13] "recent_weight_kg"        "insurance"
[15] "age"                     "English"

In [14]:
# save file cohort_demo
write.csv(cohort_demo, file = file.path(outdir, "3_coh2_demo.csv"), row.names=FALSE)