This notebook was developed by Gautam Machiraju and Conor Corbin, modified by Minh Nguyen

### Description:
- Use 2015 - 2017 as the training data to check for value distributions with 10 quantiles
- Use these distributions to assign new validation and test values to quantile bins

Input: 
- `6_9_coh4_feature_values`: used cohort4

Outputs: `...coh4...`
- `6_10_binned_labs_vitals_train`:
    - use 2015 - 2017 as trained data for value distributions to bin validation data of 2018
    - this is for the purpose of train data and select model hyper parameters on validation data
    - test data > 2018 (2019 and some 2020) left unused
- `6_10_binned_labs_vitals_test`:
    - after model hyper parameters were already selected, the value distributions are done again on data 2015 - 2018
    - test data > 2018 (2019 and some 2020) are binned on based on these distributions
    - binned test data is used for the final prediction and evaluation of model performance

In [1]:
import os 
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

In [2]:
import os 
from google.cloud import bigquery
from google.cloud.bigquery import dbapi

##Use correct path based on whether you are, Nero or local
# use Ctrl + Insert to copy and Shift + Insert to paste

# for Nero:
# os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '/home/minh084/.config/gcloud/application_default_credentials.json' 
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '/home/jupyter/.config/gcloud/application_default_credentials.json'

# for local computer:
# os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = r'C:\Users\User\AppData\Roaming\gcloud\application_default_credentials.json' 

##set correct Nero project
os.environ['GCLOUD_PROJECT'] = 'som-nero-phi-jonc101'

In [3]:
valdir = "../../OutputTD/6_validation"
cohortdir = "../../OutputTD/1_cohort"
featuredir = "../../OutputTD/2_features"

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 50)

### Train And Apply Featurizer - change for new validation data after March 2020! 

#### Depending on which dataset used for train/val or train_val/test, choose different time split
- For the purpose of training to select hyperparameters for models, use 2015 - 2017 (<2018) for binning distribution --> **NEW: use 2015 - 2018**
- One a final model with hyperparameters are selected, for the final prediction on an unseen test set, use 2015 - 2018 for binning distribution ( < 2019) --> **NEW: use 2015 - 03/2020**
- basically with this new validation data, we could use all the old data in this process, without saving the 2019 - 03/2020 as the final test set

# either pull from BQ
query = """select * from triageTD.6_9_coh4_feature_values.csv"""
query_job = client.query(query)
df = query_job.result().to_dataframe()

In [4]:
# OLD DATA up to 03/2020
df = pd.read_csv(os.path.join(featuredir, "2_7_coh4_feature_values.csv"))

# need this if read from local file, if pulled from BQ, already in datetime format
df["admit_time"] = pd.to_datetime(df["admit_time"]) 

print(len(df)) # 3,085,046

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3170: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

3085046

In [5]:
# check to see if any feature is null
df[df['features'].isnull()]

Empty DataFrame
Columns: [anon_id, pat_enc_csn_id_coded, admit_time, first_label, death_24hr_recent_label, death_24hr_max_label, feature_type, features, values, time]
Index: []

In [6]:
# df.loc[df['pat_enc_csn_id_coded'] == 131250899044]

In [7]:
df = df[df['feature_type'].isin(['labs', 'vitals'])]
df["time"] = pd.to_datetime(df["time"])

print(len(df)) #2337386

2337386

In [8]:
df.head(5)

,anon_id,pat_enc_csn_id_coded,admit_time,first_label,death_24hr_recent_label,death_24hr_max_label,feature_type,features,values,time
747660,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,0,0,0,vitals,Temp,36.9,2019-08-31 10:14:00+00:00
747661,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,0,0,0,vitals,DBP,62.0,2019-08-31 12:00:00+00:00
747662,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,0,0,0,vitals,SBP,124.0,2019-08-31 12:00:00+00:00
747663,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,0,0,0,vitals,Pulse,102.0,2019-08-31 12:00:00+00:00
747664,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,0,0,0,vitals,RR,11.0,2019-08-31 12:00:00+00:00

In [9]:
# calculate time difference in hours between admit time and time of vitals and labs,
df['difftime'] = round((df['admit_time'] - df['time']).dt.total_seconds()/3600, 1)

# check for observations more than 24 hours before admission time
print(len(df.loc[df['difftime'] > 24])) # 40070
df[['difftime']].describe()

40070

           difftime
count  2.337386e+06
mean   4.232521e+00
std    9.191640e+01
min    0.000000e+00
25%    1.300000e+00
50%    2.600000e+00
75%    4.600000e+00
max    1.401405e+05

In [10]:
# remove those observations:
df = df.loc[df['difftime'] <= 24]
print(len(df)) #2297316

# check for coh4:
2337386 - 40070

2297316

2297316

### Process Continuous Features
Create a function that "trains" binning featurizer (computes distribution of values) based on subset of the data.  This is important because we only want to build the distribution with our training set and apply the bin featurizer
to the test set (prevents leakage). 

Then create a function that "applies" the trained featurizer on a set of data.

In [11]:
def convert_to_dict(look_up_table):
    """Converts df look up table to dictionary for faster look up later"""
    bin_val_dict = {}
    for feature in look_up_table['features'].unique():
        feature_bin_vals = look_up_table[look_up_table['features'] == feature]
        for _bin in feature_bin_vals['bins'].unique():
            if feature not in bin_val_dict:
                bin_val_dict[feature] = {}
                bin_val_dict[feature]['min'] = []
                bin_val_dict[feature]['max'] = []

            min_val_for_bin = feature_bin_vals[feature_bin_vals['bins'] == _bin]['values']['min'].values[0]
            max_val_for_bin = feature_bin_vals[feature_bin_vals['bins'] == _bin]['values']['max'].values[0]

            bin_val_dict[feature]['min'].append(min_val_for_bin)
            bin_val_dict[feature]['max'].append(max_val_for_bin)
    return bin_val_dict

    
def train_featurizer(df_train):
    """
    Compute percent_ranks and generates a look up table of min and max bin values
    Input : long form dataframe with features and values where values are the continuous values of labs / vitals
    Output: look up table - dict of dict of lists (key1 = feature_name, key2 = max or min, values = lists of values)
    """
    # Compute percentiles and bins
    df_train['percentiles'] = df_train.groupby('features')['values'].transform(lambda x: x.rank(pct=True))
    df_train['bins'] = df_train['percentiles'].apply(lambda x: int(x * 10))
    
    # Generate look up table and conver to dictionary stucture
    look_up_table_df = df_train.groupby(['features', 'bins']).agg({'values' : ['min', 'max']}).reset_index()
    look_up_table = convert_to_dict(look_up_table_df)
    
    ### Sanity Check. Ensure that min vector for each feature is strictly increasing (no ties!)
    # Should be the case because ties are given same percentile rank in default pandas rank function
    for feature in look_up_table:
        mins = look_up_table[feature]['min']
        for i in range(len(mins)-1):
            assert mins[i] < mins[i+1]
    
    return look_up_table


def apply_featurizer(df, look_up_table):
    
    def get_appropriate_bin(feature, value, look_up_table):
        """Takes in feature, value and look up table and returns appropriate bin

        Quick Note: For some features, we do not have 10 bins.  This happens when we have many many ties in the 
        percent rank - and the percent rank alg returns ties as the average rank within that tie. So for instance
        we're trying to break each feature up into deciles where each bin covers range of 10% of the examples. But if more
        than 10% of the examples take on 1 value - then bins can be skipped. This shouldn't really be a problem
        for downstream tasks - just something to be aware of. This also means 'bins' and 'bins_applied' won't have
        perfect overlap in features that end up having less than 10 bins

        """
        mins = look_up_table[feature]['min']
        for i in range(len(mins) - 1):
            # If value is smaller than min value of smallest bin (in test time) - then return 0 (smallest bin)
            if i == 0 and value < mins[i]:
                return i

            if value >= mins[i] and value < mins[i+1] :
                return i

        # Then in last bin
        return len(mins)-1
    
    df['bins_applied'] = df[['features', 'values']].apply(
        lambda x: get_appropriate_bin(x['features'], x['values'], look_up_table), axis=1)
    
    return df

### Train And Apply Featurizer - change for new validation data after March 2020! 

#### Depending on which dataset used for train/val or train_val/test, choose different time split
- For the purpose of training to select hyperparameters for models, use 2015 - 2017 (<2018) for binning distribution --> **NEW: use 2015 - 2018**
- One a final model with hyperparameters are selected, for the final prediction on an unseen test set, use 2015 - 2018 for binning distribution ( < 2019) --> **NEW: use 2015 - 03/2020**
- basically with this new validation data, we could use all the old data in this process, without saving the 2019 - 03/2020 as the final test set

In [12]:
# for train/val VS. train_val/test:
# df_train =  df[(df['admit_time'].dt.year < 2019)] # old 2018
# df_train =  df[(df['admit_time'].dt.year < 2021)] # old 2019

In [13]:
# FOR TRAINING/VALIDATION purpose - chosing hyperparameters, 
# do decile distribution only on train set
df_train =  df[(df['admit_time'].dt.year < 2019)]

### OR TRAIN_VAL/TEST
# AFTER training and chosing hyperparameters, RE-DO DECILE distribution on both train_val set (2015 - 2018)
df_train =  df[(df['admit_time'].dt.year < 2021)] # all

In [14]:
# continue here
look_up_table = train_featurizer(df_train)
df_featurized = apply_featurizer(df, look_up_table)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [15]:
# sanity check of the total cohort size with time splitting
# Change the years
print(len(df))
print(len(df[(df['admit_time'].dt.year < 2019)]))
print(len(df[(df['admit_time'].dt.year == 2019)]))
print(len(df[(df['admit_time'].dt.year > 2019)]))
len(df[(df['admit_time'].dt.year < 2019)]) + len(df[(df['admit_time'].dt.year == 2019)]) + len(df[(df['admit_time'].dt.year > 2019)])

2297316
1678328
500057
118931

2297316

### Quick Sanity Check
For features that have 10 bins from 0 to 9 - `bins` should be same as `bins_applied`

In [16]:
df_train = apply_featurizer(df_train, look_up_table)
look_up_table_df = df_train.groupby(['features', 'bins']).agg({'values' : ['min', 'max']}).reset_index()

features_with_0_9_bins = []
for feature in look_up_table_df:
    num_bins = len(look_up_table_df[look_up_table_df['features'] == feature]['bins'].values)
    ten_in_bins = 10 in look_up_table_df[look_up_table_df['features'] == feature]['bins'].values
    if num_bins == 10 and not ten_in_bins:
        features_with_0_9_bins.append(feature)

for feature in features_with_0_9_bins:
    df_test = df_train[df_train['features'] == 'feature']
    for b_real, b_computed in zip(df_test['bins'].values, df_test['bins_applied'].values):
        assert(b_real == b_computed)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [17]:
# checked against R 2.9_
len(df_train) # 1678328 --old coh4: 1254522 vs 1714603

1678328

### Little bit of house cleaning
Create new feature names that reflect which bin the value belongs in

In [18]:
columns = ['anon_id', 'pat_enc_csn_id_coded', 'admit_time', 'feature_type', 'features', 'values', 'bins_applied']
df_new = df_featurized[columns]

In [19]:
df_new['features'] = ['_'.join([x, str(y)]) for x, y in zip(df_new['features'].values, df_new['bins_applied'].values)]

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [20]:
len(df_new) #coh4 2337386

2297316

### Get Counts representation
Group by patient, cns, and feature name (with bin value appended to feature name) and make value the number of times
that particular feature appears for that csn id.

In [21]:
df_final = df_new.groupby(['anon_id', 'pat_enc_csn_id_coded', 'features']).agg(
    {'admit_time' : 'first',
     'feature_type' : 'first',
     'values' : 'count'}).reset_index()

columns = ['anon_id', 'pat_enc_csn_id_coded', 'admit_time', 'feature_type', 'features', 'values']
df_final = df_final[columns] # reorder columns
 
df_final['feature_type'] = [x + '_results' if x == 'labs' else x for x in df_final['feature_type'].values]

#### Depending on which dataset used for train/val or train_val/test, name: _train vs _test
- Rename feature_type to reflect training set used: ..._train or ...test
- 'vitals_train' means everything up to 2017 (**NEW- 2018**) used. (train vs val)
- 'vitals_test' means everything up to 2018 (**NEW - 02/2020**) used. (train + val vs test)

In [22]:
# for train/val to select hyperparameters, binned distributions on train/val: 
# df_train =  df[(df['admit_time'].dt.year < 2018)]
df_final['feature_type'] = [x + '_train' for x in df_final['feature_type'].values]

### OR 2nd time on train_val/test: 
# df_train =  df[(df['admit_time'].dt.year < 2019)]
df_final['feature_type'] = [x + '_test' for x in df_final['feature_type'].values]

In [23]:
print(len(df_final)) # old - updated coh4 1825210(train) vs 1826919 (train_val)
print(len(df)) # updated coh4 2297316 same

1826919
2297316

In [24]:
# Sanity check - sum of the counts should be length of the orginal dataframe
assert df_final['values'].sum() == len(df)

In [25]:
df_final.head(10)

,anon_id,pat_enc_csn_id_coded,admit_time,feature_type,features,values
0,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,labs_results_train,ALB_3,1
1,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,labs_results_train,ALK_7,1
2,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,labs_results_train,ALT_0,1
3,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,labs_results_train,AST_1,1
4,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,labs_results_train,AnionGap_9,1
5,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,labs_results_train,BUN_8,1
6,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,labs_results_train,Base_0,2
7,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,labs_results_train,Basos_3,1
8,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,labs_results_train,CO2_0,1
9,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,labs_results_train,Ca_2,1

### SAVE, depending on which cohort and which dataset

#### cohort4, train/val, train_val/test

In [26]:
# for training to select hyperparameters: df_train =  df[(df['admit_time'].dt.year < 2019)] - new
df_final.to_csv(os.path.join(valdir, '6_10_coh4_binned_labs_vitals_train.csv'), index=False)

### OR
# after selecting hyperparameters, re-do binned distributions: df_train =  df[(df['admit_time'].dt.year < 2019)]
# df_final.to_csv(os.path.join(featuredir, '2_8_coh4_binned_labs_vitals_test.csv'), index=False)
df_final.to_csv(os.path.join(featuredir, '2_8_coh4_24hrpreadmit_binned_labs_vitals_test.csv'), index=False)

### ReDO with TRAIN_VAL/TEST

- First, format the new data 04/2020 - 2021
- Remove the bins_applied column from the old data
- Concat the 2 data into one for re-binning

In [27]:
# new data from 04/2020 - 2021
# USE cohort4, read from local storage
df21 = pd.read_csv(os.path.join(valdir, "6_9_coh4_feature_values.csv"))

# need this if read from local file, if pulled from BQ, already in datetime format
df21["admit_time"] = pd.to_datetime(df21["admit_time"]) 

print(len(df21)) # 1175680

# check if any feature is null
df[df['features'].isnull()] # NONE

# extract vitals and labs
df21 = df21[df21['feature_type'].isin(['labs', 'vitals'])]
df21["time"] = pd.to_datetime(df21["time"])

print(len(df21)) # 895452
# calculate time difference in hours between admit time and time of vitals and labs,
df21['difftime'] = round((df21['admit_time'] - df21['time']).dt.total_seconds()/3600, 1)

# check for observations more than 24 hours before admission time
print(len(df21.loc[df21['difftime'] > 24])) # 6752

# remove those observations:
df21 = df21.loc[df21['difftime'] <= 24]
print(len(df21)) # 888700

df21[['difftime']].describe()

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3170: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

1175680
895452
6752
888700

            difftime
count  888700.000000
mean        2.863723
std         2.468526
min         0.000000
25%         1.200000
50%         2.300000
75%         3.800000
max        24.000000

In [28]:
# old data up to 03/2020
print(len(df)) #2297316
df.head(3)

2297316

,anon_id,pat_enc_csn_id_coded,admit_time,first_label,death_24hr_recent_label,death_24hr_max_label,feature_type,features,values,time,difftime,bins_applied
747660,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,0,0,0,vitals,Temp,36.9,2019-08-31 10:14:00+00:00,2.6,3
747661,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,0,0,0,vitals,DBP,62.0,2019-08-31 12:00:00+00:00,0.9,2
747662,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,0,0,0,vitals,SBP,124.0,2019-08-31 12:00:00+00:00,0.9,4

In [29]:
df0 = df.drop(columns=["bins_applied"])
df0.head(1)

,anon_id,pat_enc_csn_id_coded,admit_time,first_label,death_24hr_recent_label,death_24hr_max_label,feature_type,features,values,time,difftime
747660,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,0,0,0,vitals,Temp,36.9,2019-08-31 10:14:00+00:00,2.6

In [30]:
# new data up 04/2020 - 2021
print(len(df21)) # 888700
df21.head(1)

888700

,anon_id,pat_enc_csn_id_coded,admit_time,first_label,death_24hr_recent_label,death_24hr_max_label,feature_type,features,values,time,difftime
280228,JC1000116,131295313275,2020-09-29 22:45:00+00:00,0.0,0,0,vitals,Temp,36.6,2020-09-29 15:55:00+00:00,6.8

In [31]:
### Concat 2 data frames into 1

df = pd.concat([df0,df21])
print(len(df0)) # 2297316
print(len(df21)) # 888700
print(len(df)) # 3186016

df.head(1)

2297316
888700
3186016

,anon_id,pat_enc_csn_id_coded,admit_time,first_label,death_24hr_recent_label,death_24hr_max_label,feature_type,features,values,time,difftime
747660,JC29f8ad2,131274729058,2019-08-31 12:52:00+00:00,0.0,0,0,vitals,Temp,36.9,2019-08-31 10:14:00+00:00,2.6

In [32]:
features0 = df0.features.unique()
features0.sort()
print(len(features0))
features0

49

array(['ALB', 'ALK', 'ALT', 'AST', 'AnionGap', 'BUN', 'Base', 'Basos',
       'CO2', 'Ca', 'Cl', 'Cr', 'DBP', 'Eos', 'Glob', 'Glucose', 'HCO3_a',
       'HCO3_v', 'Hct', 'Hgb', 'INR', 'K', 'Lactate', 'Lymp', 'MCH',
       'Mono', 'Na', 'Neut', 'O2sat_a', 'O2sat_v', 'PO2_a', 'PO2_v', 'PT',
       'Platelet', 'Pulse', 'RDW', 'RR', 'SBP', 'TBili', 'TCO2_a',
       'TProtein', 'Temp', 'Trop', 'WBC', 'eGFR', 'pCO2_a', 'pCO2_v',
       'pH_a', 'pH_v'], dtype=object)

In [33]:
features21 = df21.features.unique()
features21.sort()
print(len(features21))
features21

49

array(['ALB', 'ALK', 'ALT', 'AST', 'AnionGap', 'BUN', 'Base', 'Basos',
       'CO2', 'Ca', 'Cl', 'Cr', 'DBP', 'Eos', 'Glob', 'Glucose', 'HCO3_a',
       'HCO3_v', 'Hct', 'Hgb', 'INR', 'K', 'Lactate', 'Lymp', 'MCH',
       'Mono', 'Na', 'Neut', 'O2sat_a', 'O2sat_v', 'PO2_a', 'PO2_v', 'PT',
       'Platelet', 'Pulse', 'RDW', 'RR', 'SBP', 'TBili', 'TCO2_a',
       'TProtein', 'Temp', 'Trop', 'WBC', 'eGFR', 'pCO2_a', 'pCO2_v',
       'pH_a', 'pH_v'], dtype=object)

In [34]:
### OR 2nd time on TRAIN_VAL/TEST
# AFTER training and chosing hyperparameters, RE-DO DECILE distribution on both train_val set (2015 - 2018)
# df_train =  df[(df['admit_time'].dt.year < XXX)] # all old data up to 03/2020
df_train = df0 # all old data up to 03/2020
print(len(df_train)) # 2297316

# continue here
look_up_table = train_featurizer(df_train)
df_featurized = apply_featurizer(df, look_up_table)  # NOTE, df here is the combined df0 and df21

# sanity check
df_train = apply_featurizer(df_train, look_up_table)
look_up_table_df = df_train.groupby(['features', 'bins']).agg({'values' : ['min', 'max']}).reset_index()

features_with_0_9_bins = []
for feature in look_up_table_df:
    num_bins = len(look_up_table_df[look_up_table_df['features'] == feature]['bins'].values)
    ten_in_bins = 10 in look_up_table_df[look_up_table_df['features'] == feature]['bins'].values
    if num_bins == 10 and not ten_in_bins:
        features_with_0_9_bins.append(feature)

for feature in features_with_0_9_bins:
    df_test = df_train[df_train['features'] == 'feature']
    for b_real, b_computed in zip(df_test['bins'].values, df_test['bins_applied'].values):
        assert(b_real == b_computed)

# cleaning - 
# create new feature names that reflect which bin the value belongs in
columns = ['anon_id', 'pat_enc_csn_id_coded', 'admit_time', 'feature_type', 'features', 'values', 'bins_applied']
df_new = df_featurized[columns]

df_new['features'] = ['_'.join([x, str(y)]) for x, y in zip(df_new['features'].values, df_new['bins_applied'].values)] 

print(len(df_new)) #3186016

# get count presentation
df_final = df_new.groupby(['anon_id', 'pat_enc_csn_id_coded', 'features']).agg(
    {'admit_time' : 'first',
     'feature_type' : 'first',
     'values' : 'count'}).reset_index()

columns = ['anon_id', 'pat_enc_csn_id_coded', 'admit_time', 'feature_type', 'features', 'values']
df_final = df_final[columns] # reorder columns

df_final['feature_type'] = [x + '_results' if x == 'labs' else x for x in df_final['feature_type'].values]

# OR 2nd time on train-val/test: rename feature type to reflect train or test
df_final['feature_type'] = [x + '_test' for x in df_final['feature_type'].values]

print(len(df_final)) # 2534674
print(len(df)) # 3186016

# sanity check
assert df_final['values'].sum() == len(df)

### OR 2nd time on train-val/test
df_final.to_csv(os.path.join(valdir, '6_10_coh4_binned_labs_vitals_test.csv'), index=False)

2297316

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

3186016
2534674
3186016

### View

In [36]:
for feature in look_up_table_df['features'].unique():
    print(look_up_table_df[look_up_table_df['features'] == feature])

   features bins values
                    min  max
0       ALB    0    0.9  2.4
1       ALB    1    2.5  2.8
2       ALB    2    2.9  3.1
3       ALB    3    3.2  3.3
4       ALB    4    3.4  3.5
5       ALB    5    3.6  3.7
6       ALB    6    3.8  3.8
7       ALB    7    3.9  4.0
8       ALB    8    4.1  4.3
9       ALB    9    4.4  6.4
10      ALB   10    6.7  6.7
   features bins values
                    min     max
11      ALK    0   14.0    56.0
12      ALK    1   57.0    65.0
13      ALK    2   66.0    73.0
14      ALK    3   74.0    82.0
15      ALK    4   83.0    91.0
16      ALK    5   92.0   102.0
17      ALK    6  103.0   117.0
18      ALK    7  118.0   144.0
19      ALK    8  145.0   211.0
20      ALK    9  212.0  3500.0
   features bins  values
                     min     max
21      ALT    0     5.0    13.0
22      ALT    1    14.0    17.0
23      ALT    2    18.0    20.0
24      ALT    3    21.0    23.0
25      ALT    4    24.0    27.0
26      ALT    5    28.0    32.0
27      ALT    6    33.0    39.0
28      ALT    7    40.0    51.0
29      ALT    8    52.0    82.0
30      ALT    9    83.0  3500.0
31      ALT   10  4002.0  4002.0
   features bins  values
                     min     max
32      AST    0     5.0    15.0
33      AST    1    16.0    18.0
34      AST    2    19.0    21.0
35      AST    3    22.0    23.0
36      AST    4    24.0    27.0
37      AST    5    28.0    32.0
38      AST    6    33.0    39.0
39      AST    7    40.0    53.0
40      AST    8    54.0    90.0
41      AST    9    91.0  6729.0
42      AST   10  9655.0  9655.0
    features bins values
                     min   max
43  AnionGap    0    1.0   5.0
44  AnionGap    1    6.0   7.0
45  AnionGap    2    8.0   8.0
46  AnionGap    3    9.0   9.0
47  AnionGap    4   10.0  10.0
48  AnionGap    5   11.0  11.0
49  AnionGap    6   12.0  13.0
50  AnionGap    7   14.0  14.0
51  AnionGap    8   15.0  17.0
52  AnionGap    9   18.0  55.0
53  AnionGap   10   62.0  62.0
   features bins values
                    min    max
54      BUN    0    1.0    8.0
55      BUN    1    9.0   11.0
56      BUN    2   12.0   13.0
57      BUN    3   14.0   15.0
58      BUN    4   16.0   17.0
59      BUN    5   18.0   20.0
60      BUN    6   21.0   24.0
61      BUN    7   25.0   31.0
62      BUN    8   32.0   45.0
63      BUN    9   46.0  202.0
64      BUN   10  231.0  231.0
   features bins values
                    min   max
65     Base    0  -30.0  -8.0
66     Base    1   -7.9  -5.0
67     Base    2   -4.9  -3.0
68     Base    3   -2.9  -1.1
69     Base    4   -1.0   0.0
70     Base    5    0.1   1.0
71     Base    6    1.1   2.0
72     Base    7    2.1   4.0
73     Base    8    4.1   6.9
74     Base    9    7.0  30.0
75     Base   10   42.5  42.5
   features bins values
                    min    max
76    Basos    0   0.00   0.01
77    Basos    1   0.02   0.02
78    Basos    3   0.03   0.03
79    Basos    4   0.04   0.04
80    Basos    6   0.05   0.05
81    Basos    7   0.06   0.07
82    Basos    8   0.08   0.09
83    Basos    9   0.10  21.31
84    Basos   10  65.92  65.92
   features bins values
                    min   max
85      CO2    0    3.0  19.0
86      CO2    1   20.0  21.0
87      CO2    2   22.0  23.0
88      CO2    3   24.0  24.0
89      CO2    4   25.0  25.0
90      CO2    5   26.0  26.0
91      CO2    6   27.0  27.0
92      CO2    7   28.0  28.0
93      CO2    8   29.0  29.0
94      CO2    9   30.0  50.0
    features bins values
                     min   max
95        Ca    0    3.2   8.1
96        Ca    1    8.2   8.4
97        Ca    2    8.5   8.6
98        Ca    3    8.7   8.8
99        Ca    4    8.9   8.9
100       Ca    5    9.0   9.1
101       Ca    6    9.2   9.2
102       Ca    7    9.3   9.4
103       Ca    8    9.5   9.7
104       Ca    9    9.8  19.5
105       Ca   10   19.6  19.6
    features bins values
                     min    max
106       Cl    0   60.0   92.0
107       Cl    1   93.0   95.0
108       Cl    2   96.0   97.0
109       Cl    3   98.0   99.0
110       Cl    4  100.0  100.0
111       Cl    5  101.0  101.0
112       Cl    6  102.0  103.0
113       Cl    7  104.0  104.0
114       Cl    8  105.0  106.0
115       Cl    9  107.0  151.0
116       Cl   10  153.0  153.0
    features bins values
                     min    max
117       Cr    0   0.06   0.59
118       Cr    1   0.60   0.69
119       Cr    2   0.70   0.79
120       Cr    3   0.80   0.87
121       Cr    4   0.88   0.95
122       Cr    5   0.96   1.07
123       Cr    6   1.08   1.20
124       Cr    7   1.21   1.50
125       Cr    8   1.51   2.36
126       Cr    9   2.37  30.21
127       Cr   10  31.59  31.59
    features bins values
                     min    max
128      DBP    0   12.0   54.0
129      DBP    1   55.0   61.0
130      DBP    2   62.0   66.0
131      DBP    3   67.0   70.0
132      DBP    4   71.0   74.0
133      DBP    5   75.0   78.0
134      DBP    6   79.0   83.0
135      DBP    7   84.0   89.0
136      DBP    8   90.0   97.0
137      DBP    9   98.0  233.0
138      DBP   10  238.0  238.0
    features bins values
                     min    max
139      Eos    0   0.00   0.00
140      Eos    1   0.01   0.01
141      Eos    2   0.02   0.03
142      Eos    3   0.04   0.05
143      Eos    4   0.06   0.07
144      Eos    5   0.08   0.10
145      Eos    6   0.11   0.14
146      Eos    7   0.15   0.20
147      Eos    8   0.21   0.31
148      Eos    9   0.32  36.93
149      Eos   10  38.23  38.23
    features bins values
                     min   max
150     Glob    0   -0.4   2.8
151     Glob    1    2.9   3.1
152     Glob    2    3.2   3.3
153     Glob    3    3.4   3.5
154     Glob    4    3.6   3.7
155     Glob    5    3.8   3.9
156     Glob    6    4.0   4.1
157     Glob    7    4.2   4.4
158     Glob    8    4.5   4.9
159     Glob    9    5.0  12.6
160     Glob   10   15.1  15.1
    features bins  values
                      min     max
161  Glucose    0     8.0    90.0
162  Glucose    1    91.0    99.0
163  Glucose    2   100.0   106.0
164  Glucose    3   107.0   114.0
165  Glucose    4   115.0   122.0
166  Glucose    5   123.0   134.0
167  Glucose    6   135.0   151.0
168  Glucose    7   152.0   182.0
169  Glucose    8   183.0   259.0
170  Glucose    9   260.0  1454.0
171  Glucose   10  2146.0  2146.0
    features bins values
                     min   max
172   HCO3_a    0    1.8  14.2
173   HCO3_a    1   14.3  18.4
174   HCO3_a    2   18.5  20.4
175   HCO3_a    3   20.5  22.1
176   HCO3_a    4   22.2  23.5
177   HCO3_a    5   23.6  25.0
178   HCO3_a    6   25.1  26.7
179   HCO3_a    7   26.8  28.8
180   HCO3_a    8   28.9  32.5
181   HCO3_a    9   32.6  66.5
182   HCO3_a   10   70.8  70.8
    features bins values
                     min   max
183   HCO3_v    0    2.2  18.2
184   HCO3_v    1   18.3  20.8
185   HCO3_v    2   20.9  22.4
186   HCO3_v    3   22.5  23.7
187   HCO3_v    4   23.8  24.8
188   HCO3_v    5   24.9  25.9
189   HCO3_v    6   26.0  27.1
190   HCO3_v    7   27.2  28.6
191   HCO3_v    8   28.7  31.1
192   HCO3_v    9   31.2  72.9
193   HCO3_v   10   78.1  78.1
    features bins values
                     min   max
194      Hct    0    5.9  26.7
195      Hct    1   26.8  30.5
196      Hct    2   30.6  33.3
197      Hct    3   33.4  35.6
198      Hct    4   35.7  37.5
199      Hct    5   37.6  39.3
200      Hct    6   39.4  41.1
201      Hct    7   41.2  43.0
202      Hct    8   43.1  45.6
203      Hct    9   45.7  68.0
204      Hct   10   70.0  70.0
    features bins values
                     min   max
205      Hgb    0    2.0   8.6
206      Hgb    1    8.7   9.9
207      Hgb    2   10.0  10.8
208      Hgb    3   10.9  11.6
209      Hgb    4   11.7  12.3
210      Hgb    5   12.4  12.9
211      Hgb    6   13.0  13.6
212      Hgb    7   13.7  14.3
213      Hgb    8   14.4  15.2
214      Hgb    9   15.3  22.0
215      Hgb   10   22.3  22.3
    features bins values
                     min   max
216      INR    0    0.6   0.9
217      INR    1    1.0   1.0
218      INR    3    1.1   1.1
219      INR    5    1.2   1.2
220      INR    6    1.3   1.3
221      INR    7    1.4   1.4
222      INR    8    1.5   2.0
223      INR    9    2.1  60.0
    features bins values
                     min   max
224        K    0    1.7   3.3
225        K    1    3.4   3.6
226        K    2    3.7   3.7
227        K    3    3.8   3.8
228        K    4    3.9   4.0
229        K    5    4.1   4.1
230        K    6    4.2   4.3
231        K    7    4.4   4.5
232        K    8    4.6   4.9
233        K    9    5.0  10.0
    features bins values
                     min    max
234  Lactate    0   0.30   0.65
235  Lactate    1   0.66   0.85
236  Lactate    2   0.86   1.04
237  Lactate    3   1.05   1.24
238  Lactate    4   1.25   1.46
239  Lactate    5   1.47   1.74
240  Lactate    6   1.75   2.09
241  Lactate    7   2.10   2.60
242  Lactate    8   2.61   3.63
243  Lactate    9   3.64  20.00
    features bins   values
                       min      max
244     Lymp    0     0.00     0.45
245     Lymp    1     0.46     0.66
246     Lymp    2     0.67     0.85
247     Lymp    3     0.86     1.03
248     Lymp    4     1.04     1.22
249     Lymp    5     1.23     1.44
250     Lymp    6     1.45     1.70
251     Lymp    7     1.71     2.03
252     Lymp    8     2.04     2.59
253     Lymp    9     2.60  1401.00
254     Lymp   10  2736.00  2736.00
    features bins values
                     min   max
255      MCH    0   12.2  26.0
256      MCH    1   26.1  27.5
257      MCH    2   27.6  28.5
258      MCH    3   28.6  29.2
259      MCH    4   29.3  29.7
260      MCH    5   29.8  30.3
261      MCH    6   30.4  30.9
262      MCH    7   31.0  31.6
263      MCH    8   31.7  32.8
264      MCH    9   32.9  51.3
    features bins values
                     min    max
265     Mono    0   0.00   0.31
266     Mono    1   0.32   0.43
267     Mono    2   0.44   0.51
268     Mono    3   0.52   0.59
269     Mono    4   0.60   0.67
270     Mono    5   0.68   0.75
271     Mono    6   0.76   0.86
272     Mono    7   0.87   1.01
273     Mono    8   1.02   1.27
274     Mono    9   1.28  58.39
275     Mono   10  98.19  98.19
    features bins values
                     min    max
276       Na    0   96.0  129.0
277       Na    1  130.0  132.0
278       Na    2  133.0  134.0
279       Na    3  135.0  135.0
280       Na    4  136.0  136.0
281       Na    5  137.0  137.0
282       Na    6  138.0  138.0
283       Na    7  139.0  139.0
284       Na    8  140.0  141.0
285       Na    9  142.0  181.0
286       Na   10  183.0  183.0
    features bins  values
                      min     max
287     Neut    0    0.00    2.97
288     Neut    1    2.98    3.96
289     Neut    2    3.97    4.80
290     Neut    3    4.81    5.64
291     Neut    4    5.65    6.56
292     Neut    5    6.57    7.68
293     Neut    6    7.69    9.04
294     Neut    7    9.05   10.96
295     Neut    8   10.97   14.19
296     Neut    9   14.20  189.79
297     Neut   10  245.89  245.89
    features bins values
                     min    max
298  O2sat_a    0    9.0   40.0
299  O2sat_a    1   41.0   62.0
300  O2sat_a    2   63.0   80.0
301  O2sat_a    3   81.0   90.0
302  O2sat_a    4   90.1   93.7
303  O2sat_a    5   93.8   95.9
304  O2sat_a    6   96.0   97.0
305  O2sat_a    7   97.1   98.5
306  O2sat_a    8   98.6   99.9
307  O2sat_a    9  100.0  100.0
    features bins values
                     min    max
308  O2sat_v    0    4.0   25.0
309  O2sat_v    1   26.0   34.0
310  O2sat_v    2   35.0   42.1
311  O2sat_v    3   43.0   51.0
312  O2sat_v    4   51.3   58.8
313  O2sat_v    5   59.0   65.0
314  O2sat_v    6   65.3   72.0
315  O2sat_v    7   72.3   79.8
316  O2sat_v    8   80.0   87.0
317  O2sat_v    9   87.1  100.0
    features bins values
                     min    max
318    PO2_a    0    9.0   23.0
319    PO2_a    1   24.0   31.0
320    PO2_a    2   32.0   42.0
321    PO2_a    3   43.0   58.5
322    PO2_a    4   59.0   70.1
323    PO2_a    5   70.2   85.0
324    PO2_a    6   85.2  107.6
325    PO2_a    7  108.0  159.0
326    PO2_a    8  160.0  244.0
327    PO2_a    9  244.3  619.0
328    PO2_a   10  634.0  634.0
    features bins values
                     min    max
329    PO2_v    0    5.0   18.0
330    PO2_v    1   19.0   21.0
331    PO2_v    2   22.0   24.2
332    PO2_v    3   25.0   27.8
333    PO2_v    4   28.0   31.0
334    PO2_v    5   31.4   34.0
335    PO2_v    6   34.1   38.9
336    PO2_v    7   39.0   44.0
337    PO2_v    8   44.4   53.0
338    PO2_v    9   53.2  508.0
339    PO2_v   10  568.0  568.0
    features bins values
                     min    max
340       PT    0    8.2   12.7
341       PT    1   12.8   13.1
342       PT    2   13.2   13.5
343       PT    3   13.6   13.9
344       PT    4   14.0   14.3
345       PT    5   14.4   14.8
346       PT    6   14.9   15.6
347       PT    7   15.7   17.3
348       PT    8   17.4   22.3
349       PT    9   22.4  300.0
     features bins  values
                       min     max
350  Platelet    0     1.0   115.0
351  Platelet    1   116.0   156.0
352  Platelet    2   157.0   183.0
353  Platelet    3   184.0   205.0
354  Platelet    4   206.0   227.0
355  Platelet    5   228.0   250.0
356  Platelet    6   251.0   278.0
357  Platelet    7   279.0   316.0
358  Platelet    8   317.0   382.0
359  Platelet    9   383.0  3466.0
360  Platelet   10  4130.0  4130.0
    features bins values
                     min    max
361    Pulse    0   12.0   63.0
362    Pulse    1   64.0   70.0
363    Pulse    2   71.0   76.0
364    Pulse    3   77.0   81.0
365    Pulse    4   82.0   86.0
366    Pulse    5   87.0   92.0
367    Pulse    6   93.0   98.0
368    Pulse    7   99.0  105.0
369    Pulse    8  106.0  117.0
370    Pulse    9  118.0  273.0
371    Pulse   10  300.0  300.0
    features bins values
                     min   max
372      RDW    0   10.6  12.7
373      RDW    1   12.8  13.1
374      RDW    2   13.2  13.5
375      RDW    3   13.6  13.9
376      RDW    4   14.0  14.4
377      RDW    5   14.5  15.0
378      RDW    6   15.1  15.8
379      RDW    7   15.9  16.9
380      RDW    8   17.0  18.8
381      RDW    9   18.9  41.1
382      RDW   10   41.6  41.6
    features bins values
                     min   max
383       RR    0    5.0  14.0
384       RR    1   15.0  15.0
385       RR    2   16.0  16.0
386       RR    3   17.0  17.0
387       RR    4   18.0  18.0
388       RR    6   19.0  20.0
389       RR    7   21.0  21.0
390       RR    8   22.0  25.0
391       RR    9   26.0  60.0
    features bins values
                     min    max
392      SBP    0   33.0   97.0
393      SBP    1   98.0  106.0
394      SBP    2  107.0  114.0
395      SBP    3  115.0  120.0
396      SBP    4  121.0  126.0
397      SBP    5  127.0  133.0
398      SBP    6  134.0  140.0
399      SBP    7  141.0  149.0
400      SBP    8  150.0  162.0
401      SBP    9  163.0  355.0
402      SBP   10  419.0  419.0
    features bins values
                     min   max
403    TBili    0    0.1   0.2
404    TBili    1    0.3   0.3
405    TBili    3    0.4   0.4
406    TBili    4    0.5   0.5
407    TBili    5    0.6   0.6
408    TBili    6    0.7   0.7
409    TBili    7    0.8   1.0
410    TBili    8    1.1   1.6
411    TBili    9    1.7  50.0
412    TBili   10   60.7  60.7
    features bins values
                     min   max
413   TCO2_a    0    2.5  16.0
414   TCO2_a    1   16.2  20.0
415   TCO2_a    2   20.1  21.9
416   TCO2_a    3   22.0  23.0
417   TCO2_a    4   23.1  24.0
418   TCO2_a    5   24.1  25.9
419   TCO2_a    6   26.0  26.9
420   TCO2_a    7   27.0  28.7
421   TCO2_a    8   28.8  31.0
422   TCO2_a    9   31.1  59.7
423   TCO2_a   10   73.2  73.2
     features bins values
                      min   max
424  TProtein    0    1.8   6.2
425  TProtein    1    6.3   6.6
426  TProtein    2    6.7   6.8
427  TProtein    3    6.9   7.1
428  TProtein    4    7.2   7.3
429  TProtein    5    7.4   7.4
430  TProtein    6    7.5   7.7
431  TProtein    7    7.8   7.9
432  TProtein    8    8.0   8.3
433  TProtein    9    8.4  15.4
434  TProtein   10   16.7  16.7
    features bins values
                     min    max
435     Temp    0  26.00  36.00
436     Temp    1  36.10  36.50
437     Temp    2  36.60  36.70
438     Temp    3  36.80  36.95
439     Temp    5  37.00  37.00
440     Temp    7  37.10  37.10
441     Temp    8  37.15  37.90
442     Temp    9  38.00  43.00
443     Temp   10  43.40  43.40
    features bins values
                     min     max
444     Trop    0  0.000   0.000
445     Trop    1  0.010   0.010
446     Trop    3  0.017   0.017
447     Trop    4  0.018   0.019
448     Trop    5  0.020   0.033
449     Trop    6  0.034   0.082
450     Trop    7  0.083   0.100
451     Trop    8  0.101   0.240
452     Trop    9  0.241  50.000
    features bins   values
                       min      max
453      WBC    0      0.1      4.7
454      WBC    1      4.8      6.0
455      WBC    2      6.1      7.0
456      WBC    3      7.1      8.0
457      WBC    4      8.1      9.0
458      WBC    5      9.1     10.1
459      WBC    6     10.2     11.5
460      WBC    7     11.6     13.5
461      WBC    8     13.6     17.0
462      WBC    9     17.1   8000.0
463      WBC   10  11900.0  11900.0
    features bins values
                     min    max
464     eGFR    0    1.0   24.0
465     eGFR    1   25.0   42.0
466     eGFR    2   43.0   55.0
467     eGFR    3   56.0   59.0
468     eGFR    4   60.0   64.0
469     eGFR    5   65.0   79.0
470     eGFR    6   80.0   89.0
471     eGFR    7   90.0   99.0
472     eGFR    8  100.0  113.0
473     eGFR    9  114.0  253.0
474     eGFR   10  336.0  336.0
    features bins values
                     min    max
475   pCO2_a    0    6.0   29.0
476   pCO2_a    1   29.1   33.1
477   pCO2_a    2   33.2   35.8
478   pCO2_a    3   35.9   38.2
479   pCO2_a    4   38.3   40.8
480   pCO2_a    5   40.9   44.0
481   pCO2_a    6   44.1   47.2
482   pCO2_a    7   47.3   52.2
483   pCO2_a    8   52.4   64.5
484   pCO2_a    9   64.6  127.8
485   pCO2_a   10  130.0  130.0
    features bins values
                     min    max
486   pCO2_v    0    9.5   29.8
487   pCO2_v    1   29.9   33.5
488   pCO2_v    2   33.6   36.0
489   pCO2_v    3   36.1   38.1
490   pCO2_v    4   38.2   40.3
491   pCO2_v    5   40.4   42.6
492   pCO2_v    6   42.7   45.0
493   pCO2_v    7   45.1   48.1
494   pCO2_v    8   48.2   53.5
495   pCO2_v    9   53.6  130.0
    features bins values
                     min    max
496     pH_a    0  6.620  7.190
497     pH_a    1  7.200  7.260
498     pH_a    2  7.264  7.307
499     pH_a    3  7.310  7.338
500     pH_a    4  7.340  7.366
501     pH_a    5  7.367  7.389
502     pH_a    6  7.390  7.410
503     pH_a    7  7.411  7.430
504     pH_a    8  7.431  7.460
505     pH_a    9  7.466  8.540
506     pH_a   10  8.660  8.660
    features bins values
                     min    max
507     pH_v    0  6.560  7.280
508     pH_v    1  7.283  7.330
509     pH_v    2  7.331  7.358
510     pH_v    3  7.360  7.378
511     pH_v    4  7.380  7.390
512     pH_v    5  7.392  7.409
513     pH_v    6  7.410  7.420
514     pH_v    7  7.421  7.440
515     pH_v    8  7.441  7.470
516     pH_v    9  7.471  7.770
517     pH_v   10  7.870  7.870